CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT DEFAULT 'user'
);
CREATE TABLE IF NOT EXISTS eaters (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT UNIQUE NOT NULL,
    score INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS history (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  dishwashers TEXT NOT NULL,
  present TEXT NOT NULL,
  hasCooked TEXT NOT NULL,
  price REAL,
  timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);